[package]
name = "dumbbell"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = {version = "0.28.0", features = ["all-widgets"]}
crossterm = "0.28.1"
clap = "4.5.35"
serde = "1.0.219"
chrono = "0.4.40"
